name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/lab4-app .

    - name: Push image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/lab4-app
